# -*- coding: utf-8 -*-

# WARNING: Any manual changes made to this file can cause application to crash
# Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1354, 698)
        Form.setMinimumSize(QtCore.QSize(1354, 698))
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 31, 1361, 31))
        self.frame.setStyleSheet("background-color: rgb(54, 67, 66);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(146, 4, 81, 21))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Calibri\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(266, 4, 71, 21))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Calibri\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(373, 5, 61, 21))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Calibri\";")
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(10, 0, 101, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(114, 0, 31, 31))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(233, 0, 31, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(340, 0, 31, 31))
        self.label_12.setObjectName("label_12")
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(569, 5, 781, 21))
        self.listWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget.setAutoFillBackground(False)
        self.listWidget.setStyleSheet("color:white;\n"
"background-color: transparent;\n"
"\n"
"border:1px solid transparent;")
        self.listWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.listWidget.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget.setObjectName("listWidget")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(422, -4, 131, 41))
        self.label_14.setStyleSheet("font: 10pt \"Calibri\";\n"
"color:white;\n"
"background-color:rgb(84, 24, 28);\n"
"border-radius:20px;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(39, 5, 71, 21))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Calibri\";")
        self.label.setObjectName("label")
        self.pushButtonYoutube = QtWidgets.QPushButton(self.frame)
        self.pushButtonYoutube.setGeometry(QtCore.QRect(5, 0, 101, 31))
        self.pushButtonYoutube.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonYoutube.setAutoFillBackground(False)
        self.pushButtonYoutube.setStyleSheet("border:0px solid grey;\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Calibri\";")
        self.pushButtonYoutube.setText("")
        self.pushButtonYoutube.setAutoDefault(False)
        self.pushButtonYoutube.setDefault(False)
        self.pushButtonYoutube.setFlat(False)
        self.pushButtonYoutube.setObjectName("pushButtonYoutube")
        self.pushButtonFacebook = QtWidgets.QPushButton(self.frame)
        self.pushButtonFacebook.setGeometry(QtCore.QRect(112, 0, 121, 31))
        self.pushButtonFacebook.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonFacebook.setAutoFillBackground(False)
        self.pushButtonFacebook.setStyleSheet("border:0px solid grey;\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Calibri\";")
        self.pushButtonFacebook.setText("")
        self.pushButtonFacebook.setAutoDefault(False)
        self.pushButtonFacebook.setDefault(False)
        self.pushButtonFacebook.setFlat(False)
        self.pushButtonFacebook.setObjectName("pushButtonFacebook")
        self.pushButtonGoogle = QtWidgets.QPushButton(self.frame)
        self.pushButtonGoogle.setGeometry(QtCore.QRect(230, 0, 101, 31))
        self.pushButtonGoogle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonGoogle.setAutoFillBackground(False)
        self.pushButtonGoogle.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Calibri\";\n"
"border:0px solid grey;")
        self.pushButtonGoogle.setText("")
        self.pushButtonGoogle.setAutoDefault(False)
        self.pushButtonGoogle.setDefault(False)
        self.pushButtonGoogle.setFlat(False)
        self.pushButtonGoogle.setObjectName("pushButtonGoogle")
        self.pushButtonGmail = QtWidgets.QPushButton(self.frame)
        self.pushButtonGmail.setGeometry(QtCore.QRect(333, 0, 91, 31))
        self.pushButtonGmail.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonGmail.setAutoFillBackground(False)
        self.pushButtonGmail.setStyleSheet("border:0px solid grey;\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 10pt \"Calibri\";")
        self.pushButtonGmail.setText("")
        self.pushButtonGmail.setAutoDefault(False)
        self.pushButtonGmail.setDefault(False)
        self.pushButtonGmail.setFlat(False)
        self.pushButtonGmail.setObjectName("pushButtonGmail")
        self.label_9.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.listWidget.raise_()
        self.label_14.raise_()
        self.label.raise_()
        self.pushButtonYoutube.raise_()
        self.pushButtonFacebook.raise_()
        self.pushButtonGoogle.raise_()
        self.pushButtonGmail.raise_()
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(-1, 67, 1361, 631))
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setToolTipDuration(0)
        self.tabWidget.setStyleSheet("background-color: rgb(64, 147, 255);\n"
"font-family:calibri;\n"
"font-size:15px;\n"
"color: white;")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(-1, 55, 1351, 21))
        self.progressBar.setMouseTracking(False)
        self.progressBar.setStyleSheet("background-color:transparent;\n"
"border-radius: 15px;\n"
"color:red;\n"
"")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(211, 0, 791, 31))
        self.lineEdit.setToolTipDuration(0)
        self.lineEdit.setStyleSheet("background-color: transparent;\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Calibri\";")
        self.lineEdit.setText("")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(195, 0, 811, 31))
        self.lineEdit_2.setStyleSheet("background-color: rgb(99, 99, 99);\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"font: 13pt \"Calibri\";")
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(50, 0, 31, 31))
        self.label_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Calibri\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(93, 0, 31, 31))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Calibri\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(140, 0, 31, 31))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Calibri\";")
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(8, 0, 31, 31))
        self.label_5.setObjectName("label_5")
        self.pushButtonForward = QtWidgets.QPushButton(Form)
        self.pushButtonForward.setGeometry(QtCore.QRect(40, 0, 31, 31))
        self.pushButtonForward.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonForward.setAutoFillBackground(False)
        self.pushButtonForward.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Calibri\";\n"
"border:0px solid grey;")
        self.pushButtonForward.setText("")
        self.pushButtonForward.setAutoDefault(False)
        self.pushButtonForward.setDefault(False)
        self.pushButtonForward.setFlat(False)
        self.pushButtonForward.setObjectName("pushButtonForward")
        self.pushButtonRefresh = QtWidgets.QPushButton(Form)
        self.pushButtonRefresh.setGeometry(QtCore.QRect(90, 0, 31, 31))
        self.pushButtonRefresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonRefresh.setAutoFillBackground(False)
        self.pushButtonRefresh.setStyleSheet("border:0px solid grey;\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Calibri\";")
        self.pushButtonRefresh.setText("")
        self.pushButtonRefresh.setAutoDefault(False)
        self.pushButtonRefresh.setDefault(False)
        self.pushButtonRefresh.setFlat(False)
        self.pushButtonRefresh.setObjectName("pushButtonRefresh")
        self.pushButtonNewTab = QtWidgets.QPushButton(Form)
        self.pushButtonNewTab.setGeometry(QtCore.QRect(130, 0, 41, 31))
        self.pushButtonNewTab.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonNewTab.setAcceptDrops(False)
        self.pushButtonNewTab.setToolTip("")
        self.pushButtonNewTab.setStatusTip("")
        self.pushButtonNewTab.setAutoFillBackground(False)
        self.pushButtonNewTab.setStyleSheet("border:0px solid grey;\n"
"background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Calibri\";")
        self.pushButtonNewTab.setText("")
        self.pushButtonNewTab.setAutoDefault(False)
        self.pushButtonNewTab.setDefault(False)
        self.pushButtonNewTab.setFlat(False)
        self.pushButtonNewTab.setObjectName("pushButtonNewTab")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1361, 31))
        self.frame_2.setStyleSheet("background-color: rgb(255, 193, 69);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setGeometry(QtCore.QRect(1069, 0, 131, 31))
        font = QtGui.QFont()
        font.setFamily("calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(81, 81, 81);\n"
"font: 10pt \"calibri\";\n"
"\n"
"color:white;\n"
"border-radius:8px;\n"
"font-weight:bold;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame_2)
        self.lcdNumber.setGeometry(QtCore.QRect(1240, 0, 111, 31))
        self.lcdNumber.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.88, y2:0.869318, stop:0.181818 rgba(225, 36, 36, 255), stop:0.761364 rgba(0, 0, 0, 255));\n"
"color:yellow;\n"
"border:3px solid red;\n"
"")
        self.lcdNumber.setObjectName("lcdNumber")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(1020, 0, 31, 31))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setToolTipDuration(0)
        self.pushButton.setStyleSheet("background-color:transparent;\n"
"border: 0px solid grey;\n"
"\n"
"color:white;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(1023, 1, 31, 31))
        self.label_13.setStyleSheet("background-color:transparent;")
        self.label_13.setObjectName("label_13")
        self.listWidget2 = QtWidgets.QListWidget(Form)
        self.listWidget2.setGeometry(QtCore.QRect(40, 130, 611, 301))
        self.listWidget2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget2.setAutoFillBackground(False)
        self.listWidget2.setStyleSheet("color:green;\n"
"background-color: transparent;\n"
"\n"
"border:1px solid transparent;")
        self.listWidget2.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget2.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget2.setObjectName("listWidget2")
        self.pushButtonBackward = QtWidgets.QPushButton(Form)
        self.pushButtonBackward.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.pushButtonBackward.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonBackward.setAutoFillBackground(False)
        self.pushButtonBackward.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Calibri\";\n"
"border:0px solid grey;")
        self.pushButtonBackward.setText("")
        self.pushButtonBackward.setAutoDefault(False)
        self.pushButtonBackward.setDefault(False)
        self.pushButtonBackward.setFlat(False)
        self.pushButtonBackward.setObjectName("pushButtonBackward")
        self.listWidget2.raise_()
        self.frame_2.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit.raise_()
        self.progressBar.raise_()
        self.frame.raise_()
        self.tabWidget.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_5.raise_()
        self.pushButtonForward.raise_()
        self.pushButtonRefresh.raise_()
        self.pushButtonNewTab.raise_()
        self.label_13.raise_()
        self.pushButton.raise_()
        self.pushButtonBackward.raise_()

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Web Browser"))
        self.label_2.setText(_translate("Form", "Facebook"))
        self.label_3.setText(_translate("Form", "Google"))
        self.label_4.setText(_translate("Form", "Gmail"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/rsz_youtube.png\"/></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/rsz_facebook.png\"/></p></body></html>"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/rsz_search.png\"/></p></body></html>"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/rsz_gmail.png\"/></p></body></html>"))
        self.label_14.setText(_translate("Form", "Bookmarks Bar"))
        self.label.setText(_translate("Form", "Youtube"))
        self.lineEdit.setToolTip(_translate("Form", "Type here"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Search Google or type a URL"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/rsz_forward.png\"/></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/rsz_refresh.png\"/></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/rsz_add.png\"/></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/rsz_backward.png\"/></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Form", "Search Engines"))
        self.comboBox.setItemText(1, _translate("Form", "Google"))
        self.comboBox.setItemText(2, _translate("Form", "Bing"))
        self.comboBox.setItemText(3, _translate("Form", "Yahoo"))
        self.comboBox.setItemText(4, _translate("Form", "DuckDuckGo"))
        self.comboBox.setItemText(5, _translate("Form", "Ask"))
        self.pushButton.setToolTip(_translate("Form", "Bookmark this tab"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/rsz_bmark.png\"/></p></body></html>"))
import icons_rc
